overrides:
  terser: ^5.48.0
  html-minifier-terser: npm:html-minifier-next
  vite: ^8.1.0
  lightningcss: ^1.32.0

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@bruits/satteri-darwin-arm64@0.9.3'
  - '@bruits/satteri-darwin-x64@0.9.3'
  - '@bruits/satteri-linux-arm64-gnu@0.9.3'
  - '@bruits/satteri-linux-arm64-musl@0.9.3'
  - '@bruits/satteri-linux-x64-gnu@0.9.3'
  - '@bruits/satteri-linux-x64-musl@0.9.3'
  - '@bruits/satteri-wasm32-wasi@0.9.3'
  - '@bruits/satteri-win32-arm64-msvc@0.9.3'
  - '@bruits/satteri-win32-x64-msvc@0.9.3'
  - satteri@0.9.3
